from enum import StrEnum


class SmashGames(StrEnum):
    SSB = '64'
    MELEE = 'Melee'
    BRAWL = 'Brawl'
    THREE_DS = '3DS'
    WII_U = 'Wii U'


class Series(StrEnum):
    ARMS = 'ARMS'
    ANIMAL_CROSSING = 'Animal Crossing'
    BALLOON_FIGHT = 'Balloon Fight'
    BANJO_KAZOOIE = 'Banjo-Kazooie'
    BAYONETTA = 'Bayonetta'
    CASTLEVANIA = 'Castlevania'
    DONKEY_KONG = 'Donkey Kong'
    DRAGON_QUEST = 'Dragon Quest'
    DUCK_HUNT = 'Duck Hunt'
    EARTHBOUND = 'EarthBound'
    ELECTROPLANKTON = 'Electroplankton'
    F_ZERO = 'F-Zero'
    FATAL_FURY = 'Fatal Fury'
    FINAL_FANTASY = 'Final Fantasy'
    FIRE_EMBLEM = 'Fire Emblem'
    GAME_AND_WATCH = 'Game & Watch'
    ICE_CLIMBER = 'Ice Climber'
    KID_ICARUS = 'Kid Icarus'
    KINGDOM_HEARTS = 'Kingdom Hearts'
    KIRBY = 'Kirby'
    MARIO = 'Mario'
    MEGA_MAN = 'Mega Man'
    METAL_GEAR = 'Metal Gear'
    METROID = 'Metroid'
    MINECRAFT = 'Minecraft'
    NINTENDO_DS = 'Nintendo DS'
    NINTENDOGS = 'Nintendogs'
    PAC_MAN = 'Pac-Man'
    PERSONA = 'Persona'
    PIKMIN = 'Pikmin'
    PILOTWINGS = 'Pilotwings'
    POKEMON = 'Pokémon'
    PUNCH_OUT = 'Punch-Out!!'
    ROB = 'R.O.B.'
    SONIC = 'Sonic the Hedgehog'
    SPLATOON = 'Splatoon'
    STAR_FOX = 'Star Fox'
    STREET_FIGHTER = 'Street Fighter'
    STREETPASS_MII_PLAZA = 'StreetPass Mii Plaza'
    SUPER_SMASH_BROS = 'Super Smash Bros.'
    TEKKEN = 'Tekken'
    THE_LEGEND_OF_ZELDA = 'The Legend of Zelda'
    TOMODACHI = 'Tomodachi'
    WARIO = 'Wario'
    WII_FIT = 'Wii Fit'
    WII_SPORTS = 'Wii Sports'
    WRECKING_CREW = 'Wrecking Crew'
    XENOBLADE_CHRONICLES = 'Xenoblade Chronicles'
    YOSHI = 'Yoshi'