name: Run pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      R2_URL: ${{ vars.R2_URL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: "3.12"

    - name: Install dependencies
      run: uv sync
      env:
        UV_LINK_MODE: copy

    - name: Run pytest
      run: uv run pytest --cov --cov-report=json

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
